# Generated by Django 4.2.1 on 2023-06-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_snippet_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='tag_name',
        ),
    ]
